/* Sample Category */
INSERT INTO BOARD_CATEGORY (CATEGORY_ID, CATEGORY_NAME, CATEGORY_CLASS1, CATEGORY_CLASS2, CATEGORY_DESCRIPTION, CATEGORY_ORDER)
VALUES(SEQ_BOARD_CATEGORY_ID.NEXTVAL, '공지사항', 1, 10, '공지사항', 100);

INSERT INTO BOARD_CATEGORY (CATEGORY_ID, CATEGORY_NAME, CATEGORY_CLASS1, CATEGORY_CLASS2, CATEGORY_DESCRIPTION, CATEGORY_ORDER)
VALUES(SEQ_BOARD_CATEGORY_ID.NEXTVAL, '자바', 2, 20, '자바', 200);

COMMIT;

